-- MySQL Script generated by MySQL Workbench
-- Tue Oct 22 05:45:54 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema EN-Fitness
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema EN-Fitness
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `EN-Fitness` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `EN-Fitness` ;

-- -----------------------------------------------------
-- Table `EN-Fitness`.`Alunos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EN-Fitness`.`Alunos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `EN-Fitness`.`Alunos` (
  `id` VARCHAR(10) NULL,
  `nome` VARCHAR(45) NOT NULL,
  `matricula` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  `curso` VARCHAR(45) NOT NULL,
  `dataNascimento` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `EN-Fitness`.`Professores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EN-Fitness`.`Professores` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `EN-Fitness`.`Professores` (
  `id` VARCHAR(10) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `especialidade` VARCHAR(45) NULL,
  `email` VARCHAR(45) NOT NULL,
  `telefone` INT NOT NULL,
  `salario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `EN-Fitness`.`Pagamentos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EN-Fitness`.`Pagamentos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `EN-Fitness`.`Pagamentos` (
  `id` VARCHAR(10) NOT NULL,
  `valor` VARCHAR(45) NOT NULL,
  `dataPagamento` DATE NOT NULL,
  `metodoPagamento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `id_aluno`
    FOREIGN KEY (`id`)
    REFERENCES `EN-Fitness`.`Alunos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `EN-Fitness`.`Alunos-Professores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EN-Fitness`.`Alunos-Professores` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `EN-Fitness`.`Alunos-Professores` (
  `id_aluno` VARCHAR(10) NOT NULL,
  `id_professor` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id_aluno`, `id_professor`),
  INDEX `id_professor_idx` (`id_professor` ASC) VISIBLE,
  CONSTRAINT `id_aluno`
    FOREIGN KEY (`id_aluno`)
    REFERENCES `EN-Fitness`.`Alunos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_professor`
    FOREIGN KEY (`id_professor`)
    REFERENCES `EN-Fitness`.`Professores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
